workflows:
  flutter-app:
    name: Flutter App CI
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
